case "${ZELLIJ_THEME:-default}" in
  ash)
    export ZELLIJ_COLOR_CRUST="#050505"
    export ZELLIJ_COLOR_MANTLE="#080808"
    export ZELLIJ_COLOR_BASE="#0f0f0f"
    export ZELLIJ_COLOR_SURFACE_DARK="#0f0f0f"
    export ZELLIJ_COLOR_SURFACE0="#1a1a1a"
    export ZELLIJ_COLOR_SURFACE1="#202020"
    export ZELLIJ_COLOR_SURFACE2="#2a2a2a"
    export ZELLIJ_COLOR_BLACK="#080808"
    export ZELLIJ_COLOR_GRAY="#3a3a3a"

    export ZELLIJ_COLOR_OVERLAY0="#444444"
    export ZELLIJ_COLOR_OVERLAY1="#555555"
    export ZELLIJ_COLOR_OVERLAY2="#666666"

    export ZELLIJ_COLOR_SUBTEXT0="#888888"
    export ZELLIJ_COLOR_SUBTEXT1="#a8a8a8"
    export ZELLIJ_COLOR_TEXT="#c8c8c8"
    export ZELLIJ_COLOR_SILVER="#c8c8c8"
    export ZELLIJ_COLOR_SILVER_LIGHT="#e8e8e8"

    export ZELLIJ_COLOR_RED="#e05c3a"
    export ZELLIJ_COLOR_MAROON="#c84828"
    export ZELLIJ_COLOR_ROSEWATER="#d4806a"
    export ZELLIJ_COLOR_FLAMINGO="#c8704a"
    export ZELLIJ_COLOR_PEACH="#e07b3a"
    export ZELLIJ_COLOR_GOLD="#d4a472"
    export ZELLIJ_COLOR_YELLOW="#d4a472"
    export ZELLIJ_COLOR_GREEN="#aaaaaa"
    export ZELLIJ_COLOR_TEAL="#a8a8a8"
    export ZELLIJ_COLOR_SKY="#b8b8b8"
    export ZELLIJ_COLOR_SAPPHIRE="#999999"
    export ZELLIJ_COLOR_BLUE="#c8c8c8"
    export ZELLIJ_COLOR_LAVENDER="#d0c0b8"
    export ZELLIJ_COLOR_MAUVE="#b09090"
    export ZELLIJ_COLOR_PINK="#c09080"
    ;;

  chalk)
    export ZELLIJ_COLOR_CRUST="#ddd8d0"
    export ZELLIJ_COLOR_MANTLE="#e5e0d8"
    export ZELLIJ_COLOR_BASE="#ede9e3"
    export ZELLIJ_COLOR_SURFACE_DARK="#f5f2ee"
    export ZELLIJ_COLOR_SURFACE0="#ede9e3"
    export ZELLIJ_COLOR_SURFACE1="#e5e0d8"
    export ZELLIJ_COLOR_SURFACE2="#ddd8d0"
    export ZELLIJ_COLOR_BLACK="#f5f2ee"
    export ZELLIJ_COLOR_GRAY="#ccc8c0"

    export ZELLIJ_COLOR_OVERLAY0="#aaa49c"
    export ZELLIJ_COLOR_OVERLAY1="#999388"
    export ZELLIJ_COLOR_OVERLAY2="#888078"

    export ZELLIJ_COLOR_SUBTEXT0="#666058"
    export ZELLIJ_COLOR_SUBTEXT1="#555048"
    export ZELLIJ_COLOR_TEXT="#2a2520"
    export ZELLIJ_COLOR_SILVER="#2a2520"
    export ZELLIJ_COLOR_SILVER_LIGHT="#1a1a1a"

    export ZELLIJ_COLOR_RED="#1a1a1a"
    export ZELLIJ_COLOR_MAROON="#2a2520"
    export ZELLIJ_COLOR_ROSEWATER="#8a7060"
    export ZELLIJ_COLOR_FLAMINGO="#7a6050"
    export ZELLIJ_COLOR_PEACH="#6a5040"
    export ZELLIJ_COLOR_GOLD="#7a6848"
    export ZELLIJ_COLOR_YELLOW="#555048"
    export ZELLIJ_COLOR_GREEN="#888078"
    export ZELLIJ_COLOR_TEAL="#777068"
    export ZELLIJ_COLOR_SKY="#888888"
    export ZELLIJ_COLOR_SAPPHIRE="#777068"
    export ZELLIJ_COLOR_BLUE="#666058"
    export ZELLIJ_COLOR_LAVENDER="#7a7068"
    export ZELLIJ_COLOR_MAUVE="#888078"
    export ZELLIJ_COLOR_PINK="#8a7870"
    ;;

  default)
    export ZELLIJ_COLOR_ROSEWATER="#f5e0dc"
    export ZELLIJ_COLOR_FLAMINGO="#f2cdcd"
    export ZELLIJ_COLOR_PINK="#f5c2e7"
    export ZELLIJ_COLOR_MAUVE="#cba6f7"
    export ZELLIJ_COLOR_RED="#f38ba8"
    export ZELLIJ_COLOR_MAROON="#eba0ac"
    export ZELLIJ_COLOR_PEACH="#fab387"
    export ZELLIJ_COLOR_YELLOW="#f9e2af"
    export ZELLIJ_COLOR_GREEN="#a6e3a1"
    export ZELLIJ_COLOR_TEAL="#94e2d5"
    export ZELLIJ_COLOR_SKY="#89dceb"
    export ZELLIJ_COLOR_SAPPHIRE="#74c7ec"
    export ZELLIJ_COLOR_BLUE="#89b4fa"
    export ZELLIJ_COLOR_LAVENDER="#b4befe"
    export ZELLIJ_COLOR_TEXT="#cdd6f4"
    export ZELLIJ_COLOR_SUBTEXT1="#bac2de"
    export ZELLIJ_COLOR_SUBTEXT0="#a6adc8"
    export ZELLIJ_COLOR_OVERLAY2="#9399b2"
    export ZELLIJ_COLOR_OVERLAY1="#7f849c"
    export ZELLIJ_COLOR_OVERLAY0="#6c7086"
    export ZELLIJ_COLOR_SURFACE2="#585b70"
    export ZELLIJ_COLOR_SURFACE1="#45475a"
    export ZELLIJ_COLOR_SURFACE0="#313244"
    export ZELLIJ_COLOR_SURFACE_DARK="#282737"
    export ZELLIJ_COLOR_BASE="#1e1e2e"
    export ZELLIJ_COLOR_MANTLE="#181825"
    export ZELLIJ_COLOR_CRUST="#11111b"
    export ZELLIJ_COLOR_SILVER="#bfc6d4"
    export ZELLIJ_COLOR_GOLD="#fae3b0"
    export ZELLIJ_COLOR_SILVER_LIGHT="#d9e0ee"
    export ZELLIJ_COLOR_BLACK="#080808"
    export ZELLIJ_COLOR_GRAY="#595b70"
    ;;

  *)
    echo "Unknown theme: $1"
    echo "Available: catppuccin (default), ash, chalk"
    return 1
    ;;
esac
